baseURL = "http://teffa.dev/"
languageCode = "en"
defaultContentLanguage = "en"
title = "Blog"
enableRobotsTXT = true
theme = "even"

[author]                  # essential
  name = "rafael"

[sitemap]                 # essential
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"


[[menu.main]]             # config your menu
  name = "Home"
  weight = 10
  url = "/"
[[menu.main]]
  name = "Tech"
  weight = 20
  url = "/categories/tech/"
[[menu.main]]
  name = "Food"
  weight = 30
  url = "/categories/food/"
[[menu.main]]
  name = "Places"
  weight = 40
  url = "/categories/places/"
[[menu.main]]
  name = "DIY"
  weight = 50
  url = "/categories/diy/"
[[menu.main]]
  name = "About"
  weight = 60
  url = "/ops/"

[params]
  version = "4.x"           # Used to give a friendly message when you have an incompatible update
  debug = false             # If true, load `eruda.min.js`. See https://github.com/liriliri/eruda
  since = "2019"            # Site creation time

  # site info (optional)
  logoTitle = "Blog"        # default: the title value
  keywords = ["tech", "food", "diy"]
  description = "A simple blog"

  # paginate of archives, tags and categories
  archivePaginate = 50

  fancybox = true           # see https://github.com/fancyapps/fancybox , see customJS below

  # Link custom CSS and JS assets
  #   (relative to /static/css and /static/js respectively)
  customCSS = []
  customJS = ['custom-fancybox.js']

  # CDN for images 
  cdnBaseURL = "https://cdn.teffa.dev"
  cdnLocalAssetPrefix = "/cdn/"

  [params.publicCDN]        # load these files from public cdn
    enable = true
    jquery = '<script src="https://cdn.jsdelivr.net/npm/jquery@3.2.1/dist/jquery.min.js" integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>'
    slideout = '<script src="https://cdn.jsdelivr.net/npm/slideout@1.0.1/dist/slideout.min.js" integrity="sha256-t+zJ/g8/KXIJMjSVQdnibt4dlaDxc9zXr/9oNPeWqdg=" crossorigin="anonymous"></script>'
    fancyboxJS = '<script src="https://cdn.jsdelivr.net/npm/@fancyapps/fancybox@3.1.20/dist/jquery.fancybox.min.js" integrity="sha256-XVLffZaxoWfGUEbdzuLi7pwaUJv1cecsQJQqGLe7axY=" crossorigin="anonymous"></script>'
    fancyboxCSS = '<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fancyapps/fancybox@3.1.20/dist/jquery.fancybox.min.css" integrity="sha256-7TyXnr2YU040zfSP+rEcz29ggW4j56/ujTPwjMzyqFY=" crossorigin="anonymous">'
    timeagoJS = '<script src="https://cdn.jsdelivr.net/npm/timeago.js@3.0.2/dist/timeago.min.js" integrity="sha256-jwCP0NAdCBloaIWTWHmW4i3snUNMHUNO+jr9rYd2iOI=" crossorigin="anonymous"></script>'
    timeagoLocalesJS = '<script src="https://cdn.jsdelivr.net/npm/timeago.js@3.0.2/dist/timeago.locales.min.js" integrity="sha256-ZwofwC1Lf/faQCzN7nZtfijVV6hSwxjQMwXL4gn9qU8=" crossorigin="anonymous"></script>'
    flowchartDiagramsJS = '<script src="https://cdn.jsdelivr.net/npm/raphael@2.2.7/raphael.min.js" integrity="sha256-67By+NpOtm9ka1R6xpUefeGOY8kWWHHRAKlvaTJ7ONI=" crossorigin="anonymous"></script> <script src="https://cdn.jsdelivr.net/npm/flowchart.js@1.8.0/release/flowchart.min.js" integrity="sha256-zNGWjubXoY6rb5MnmpBNefO0RgoVYfle9p0tvOQM+6k=" crossorigin="anonymous"></script>'
    sequenceDiagramsCSS = '<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/bramp/js-sequence-diagrams@2.0.1/dist/sequence-diagram-min.css" integrity="sha384-6QbLKJMz5dS3adWSeINZe74uSydBGFbnzaAYmp+tKyq60S7H2p6V7g1TysM5lAaF" crossorigin="anonymous">'
    sequenceDiagramsJS = '<script src="https://cdn.jsdelivr.net/npm/webfontloader@1.6.28/webfontloader.js" integrity="sha256-4O4pS1SH31ZqrSO2A/2QJTVjTPqVe+jnYgOWUVr7EEc=" crossorigin="anonymous"></script> <script src="https://cdn.jsdelivr.net/npm/snapsvg@0.5.1/dist/snap.svg-min.js" integrity="sha256-oI+elz+sIm+jpn8F/qEspKoKveTc5uKeFHNNVexe6d8=" crossorigin="anonymous"></script> <script src="https://cdn.jsdelivr.net/npm/underscore@1.8.3/underscore-min.js" integrity="sha256-obZACiHd7gkOk9iIL/pimWMTJ4W/pBsKu+oZnSeBIek=" crossorigin="anonymous"></script> <script src="https://cdn.jsdelivr.net/gh/bramp/js-sequence-diagrams@2.0.1/dist/sequence-diagram-min.js" integrity="sha384-8748Vn52gHJYJI0XEuPB2QlPVNUkJlJn9tHqKec6J3q2r9l8fvRxrgn/E5ZHV0sP" crossorigin="anonymous"></script>'

  [params.social]
    a-email = "mailto:rafael.s.carreirar@gmail.com"
    e-linkedin = "https://www.linkedin.com/in/rafaelcarreira"
    g-github = "https://github.com/rafael747"

# see https://gohugo.io/getting-started/configuration-markup
[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = true
    noClasses = false
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

